wandb_version: 1

S:
  desc: null
  value: 4
beta:
  desc: null
  value: 1.0
batch_size:
  desc: null
  value: 32
num_iters:
  desc: null
  value: 50000
lr:
  desc: null
  value: 0.001
lr_decay:
  desc: null
  value: 0.9
lr_decay_every:
  desc: null
  value: 1000
experiment-name:
  desc: null
  value: decoders
_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1701783574.929708
    t:
      1:
      - 1
      - 41
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.9.18
      5: 0.15.4
      8:
      - 2
      - 5
